const imagenes = [
  {
    name: "imagen1",
    ruta: "../img/img1.png",
  },
  {
    name: "imagen2",
    ruta: "../img/img2.png",
  },
  {
    name: "imagen3",
    ruta: "../img/img3.png",
  },
  {
    name: "imagen4",
    ruta: "../img/img4.png",
  },
  {
    name: "imagen5",
    ruta: "../img/img5.png",
  },
  {
    name: "imagen6",
    ruta: "../img/img6.png",
  },
  {
    name: "imagen7",
    ruta: "../img/img7.png",
  },
  {
    name: "imagen8",
    ruta: "../img/img8.png",
  },
  {
    name: "imagen9",
    ruta: "../img/img9.png",
  },
  {
    name: "imagen10",
    ruta: "../img/img10.png",
  },
];
const perfumes = [
  {
    id: 1,
    nombre: "Limón Spark",
    categoria: "Cítrico",
    imagen: "../img/img7.png",
    codigo: "LI37R8",
    precio: 110000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Femenino",
    temporada: "Verano",
    stock: 35,
  },
  {
    id: 2,
    nombre: "Rosa Bloom",
    categoria: "Floral",
    imagen: "../img/img1.png",
    codigo: "RO61G2",
    precio: 70000,
    volumen: 100,
    intensidad: "Media",
    genero: "Femenino",
    temporada: "Primavera",
    stock: 52,
  },
  {
    id: 3,
    nombre: "Sándalo Wood",
    categoria: "Amaderado",
    imagen: "../img/img3.png",
    codigo: "SA12X5",
    precio: 90000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Otoño",
    stock: 18,
  },
  {
    id: 4,
    nombre: "Ámbar Spice",
    categoria: "Oriental",
    imagen: "../img/img9.png",
    codigo: "AM88Z1",
    precio: 100000,
    volumen: 50,
    intensidad: "Media",
    genero: "Unisex",
    temporada: "Invierno",
    stock: 41,
  },
  {
    id: 5,
    nombre: "Manzana Kiss",
    categoria: "Frutal",
    imagen: "../img/img5.png",
    codigo: "MA29V7",
    precio: 60000,
    volumen: 100,
    intensidad: "Suave",
    genero: "Femenino",
    temporada: "Verano",
    stock: 25,
  },
  {
    id: 6,
    nombre: "Caramelo Delight",
    categoria: "Gourmand",
    imagen: "../img/img2.png",
    codigo: "CA55B3",
    precio: 80000,
    volumen: 30,
    intensidad: "Media",
    genero: "Unisex",
    temporada: "Otoño",
    stock: 12,
  },
  {
    id: 7,
    nombre: "Naranja Zest",
    categoria: "Cítrico",
    imagen: "../img/img8.png",
    codigo: "NA71Q9",
    precio: 70000,
    volumen: 100,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Primavera",
    stock: 48,
  },
  {
    id: 8,
    nombre: "Jazmín Petal",
    categoria: "Floral",
    imagen: "../img/img4.png",
    codigo: "JA93L6",
    precio: 110000,
    volumen: 30,
    intensidad: "Suave",
    genero: "Femenino",
    temporada: "Primavera",
    stock: 29,
  },
  {
    id: 9,
    nombre: "Vetiver Forest",
    categoria: "Amaderado",
    imagen: "../img/img10.png",
    codigo: "VE42M1",
    precio: 80000,
    volumen: 50,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Invierno",
    stock: 55,
  },
  {
    id: 10,
    nombre: "Vainilla Silk",
    categoria: "Oriental",
    imagen: "../img/img6.png",
    codigo: "VA19S7",
    precio: 90000,
    volumen: 100,
    intensidad: "Fuerte",
    genero: "Unisex",
    temporada: "Otoño",
    stock: 31,
  },
  {
    id: 11,
    nombre: "Pera Tart",
    categoria: "Frutal",
    imagen: "../img/img2.png",
    codigo: "PE77D4",
    precio: 50000,
    volumen: 30,
    intensidad: "Suave",
    genero: "Femenino",
    temporada: "Verano",
    stock: 15,
  },
  {
    id: 12,
    nombre: "Chocolate Dream",
    categoria: "Gourmand",
    imagen: "../img/img9.png",
    codigo: "CH33F8",
    precio: 70000,
    volumen: 50,
    intensidad: "Media",
    genero: "Unisex",
    temporada: "Invierno",
    stock: 40,
  },
  {
    id: 13,
    nombre: "Mandarina Burst",
    categoria: "Cítrico",
    imagen: "../img/img5.png",
    codigo: "MA65J2",
    precio: 100000,
    volumen: 100,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Primavera",
    stock: 22,
  },
  {
    id: 14,
    nombre: "Lavanda Dew",
    categoria: "Floral",
    imagen: "../img/img1.png",
    codigo: "LA21K9",
    precio: 60000,
    volumen: 30,
    intensidad: "Suave",
    genero: "Femenino",
    temporada: "Verano",
    stock: 58,
  },
  {
    id: 15,
    nombre: "Pachulí Ground",
    categoria: "Amaderado",
    imagen: "../img/img7.png",
    codigo: "PA98H3",
    precio: 90000,
    volumen: 50,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Otoño",
    stock: 39,
  },
  {
    id: 16,
    nombre: "Incienso Gold",
    categoria: "Oriental",
    imagen: "../img/img3.png",
    codigo: "IN54T6",
    precio: 110000,
    volumen: 100,
    intensidad: "Fuerte",
    genero: "Unisex",
    temporada: "Invierno",
    stock: 11,
  },
  {
    id: 17,
    nombre: "Frambuesa Juice",
    categoria: "Frutal",
    imagen: "../img/img10.png",
    codigo: "FR16Y1",
    precio: 80000,
    volumen: 30,
    intensidad: "Suave",
    genero: "Femenino",
    temporada: "Primavera",
    stock: 45,
  },
  {
    id: 18,
    nombre: "Café Indulge",
    categoria: "Gourmand",
    imagen: "../img/img6.png",
    codigo: "CA82W7",
    precio: 50000,
    volumen: 50,
    intensidad: "Media",
    genero: "Unisex",
    temporada: "Verano",
    stock: 28,
  },
  {
    id: 19,
    nombre: "Bergamota Fizz",
    categoria: "Cítrico",
    imagen: "../img/img4.png",
    codigo: "BE49U4",
    precio: 70000,
    volumen: 100,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Otoño",
    stock: 19,
  },
  {
    id: 20,
    nombre: "Peonía Velvet",
    categoria: "Floral",
    imagen: "../img/img8.png",
    codigo: "PE73O2",
    precio: 90000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Otoño",
    stock: 19,
  },

  {
    id: 21,
    nombre: "Guayaco Earth",
    categoria: "Amaderado",
    imagen: "../img/img2.png",
    codigo: "GU25I8",
    precio: 100000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Primavera",
    stock: 33,
  },
  {
    id: 22,
    nombre: "Mirra Mystic",
    categoria: "Oriental",
    imagen: "../img/img9.png",
    codigo: "MI51N5",
    precio: 60000,
    volumen: 100,
    intensidad: "Media",
    genero: "Femenino",
    temporada: "Verano",
    stock: 47,
  },
  {
    id: 23,
    nombre: "Melocotón Nectar",
    categoria: "Frutal",
    imagen: "../img/img5.png",
    codigo: "ME87A9",
    precio: 80000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Otoño",
    stock: 14,
  },
  {
    id: 24,
    nombre: "Almendra Treat",
    categoria: "Gourmand",
    imagen: "../img/img1.png",
    codigo: "AL13C2",
    precio: 90000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Invierno",
    stock: 51,
  },
  {
    id: 25,
    nombre: "Pomelo Glow",
    categoria: "Cítrico",
    imagen: "../img/img7.png",
    codigo: "PO44E6",
    precio: 70000,
    volumen: 100,
    intensidad: "Media",
    genero: "Femenino",
    temporada: "Primavera",
    stock: 26,
  },
  {
    id: 26,
    nombre: "Lirio Whisper",
    categoria: "Floral",
    imagen: "../img/img3.png",
    codigo: "LI70G1",
    precio: 110000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Verano",
    stock: 38,
  },
  {
    id: 27,
    nombre: "Cedro Bark",
    categoria: "Amaderado",
    imagen: "../img/img10.png",
    codigo: "CE96D7",
    precio: 80000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Otoño",
    stock: 17,
  },
  {
    id: 28,
    nombre: "Cardamomo Secret",
    categoria: "Oriental",
    imagen: "../img/img6.png",
    codigo: "CA32R3",
    precio: 100000,
    volumen: 100,
    intensidad: "Media",
    genero: "Femenino",
    temporada: "Invierno",
    stock: 42,
  },
  {
    id: 29,
    nombre: "Higo Bliss",
    categoria: "Frutal",
    imagen: "../img/img4.png",
    codigo: "HI68Z8",
    precio: 60000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Masculino",
    temporada: "Primavera",
    stock: 21,
  },
  {
    id: 30,
    nombre: "Vainilla Sensation",
    categoria: "Gourmand",
    imagen: "../img/img8.png",
    codigo: "VA94X5",
    precio: 90000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Verano",
    stock: 59,
  },
  {
    id: 31,
    nombre: "Limón Zest",
    categoria: "Cítrico",
    imagen: "../img/img2.png",
    codigo: "LI27B1",
    precio: 110000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Otoño",
    stock: 30,
  },
  {
    id: 32,
    nombre: "Rosa Petal",
    categoria: "Floral",
    imagen: "../img/img9.png",
    codigo: "RO53N7",
    precio: 70000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Invierno",
    stock: 16,
  },
  {
    id: 33,
    nombre: "Sándalo Ground",
    categoria: "Amaderado",
    imagen: "../img/img5.png",
    codigo: "SA89V4",
    precio: 80000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Primavera",
    stock: 49,
  },
  {
    id: 34,
    nombre: "Ámbar Silk",
    categoria: "Oriental",
    imagen: "../img/img1.png",
    codigo: "AM15Q8",
    precio: 90000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Verano",
    stock: 23,
  },
  {
    id: 35,
    nombre: "Manzana Tart",
    categoria: "Frutal",
    imagen: "../img/img7.png",
    codigo: "MA41L2",
    precio: 50000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Otoño",
    stock: 56,
  },
  {
    id: 36,
    nombre: "Caramelo Dream",
    categoria: "Gourmand",
    imagen: "../img/img3.png",
    codigo: "CA77U9",
    precio: 70000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Invierno",
    stock: 10,
  },
  {
    id: 37,
    nombre: "Naranja Burst",
    categoria: "Cítrico",
    imagen: "../img/img10.png",
    codigo: "NA93O5",
    precio: 100000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Primavera",
    stock: 37,
  },
  {
    id: 38,
    nombre: "Jazmín Dew",
    categoria: "Floral",
    imagen: "../img/img6.png",
    codigo: "JA29I1",
    precio: 60000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Verano",
    stock: 20,
  },
  {
    id: 39,
    nombre: "Vetiver Earth",
    categoria: "Amaderado",
    imagen: "../img/img4.png",
    codigo: "VE55C7",
    precio: 90000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Otoño",
    stock: 53,
  },
  {
    id: 40,
    nombre: "Vainilla Gold",
    categoria: "Oriental",
    imagen: "../img/img8.png",
    codigo: "VA81R4",
    precio: 110000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Invierno",
    stock: 32,
  },
  {
    id: 41,
    nombre: "Pera Juice",
    categoria: "Frutal",
    imagen: "../img/img2.png",
    codigo: "PE17Z9",
    precio: 80000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Primavera",
    stock: 13,
  },
  {
    id: 42,
    nombre: "Chocolate Indulge",
    categoria: "Gourmand",
    imagen: "../img/img9.png",
    codigo: "CH43X6",
    precio: 50000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Verano",
    stock: 46,
  },
  {
    id: 43,
    nombre: "Mandarina Fizz",
    categoria: "Cítrico",
    imagen: "../img/img5.png",
    codigo: "MA79B3",
    precio: 70000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Otoño",
    stock: 27,
  },
  {
    id: 44,
    nombre: "Lavanda Velvet",
    categoria: "Floral",
    imagen: "../img/img1.png",
    codigo: "LA35N1",
    precio: 90000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Invierno",
    stock: 50,
  },
  {
    id: 45,
    nombre: "Pachulí Bark",
    categoria: "Amaderado",
    imagen: "../img/img7.png",
    codigo: "PA61Q7",
    precio: 110000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Primavera",
    stock: 19,
  },
  {
    id: 46,
    nombre: "Incienso Mystic",
    categoria: "Oriental",
    imagen: "../img/img3.png",
    codigo: "IN97L4",
    precio: 80000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Verano",
    stock: 43,
  },
  {
    id: 47,
    nombre: "Frambuesa Bliss",
    categoria: "Frutal",
    imagen: "../img/img10.png",
    codigo: "FR23U8",
    precio: 60000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Otoño",
    stock: 24,
  },
  {
    id: 48,
    nombre: "Café Treat",
    categoria: "Gourmand",
    imagen: "../img/img6.png",
    codigo: "CA59O2",
    precio: 100000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Invierno",
    stock: 57,
  },
  {
    id: 49,
    nombre: "Bergamota Glow",
    categoria: "Cítrico",
    imagen: "../img/img4.png",
    codigo: "BE85D9",
    precio: 90000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Primavera",
    stock: 34,
  },
  {
    id: 50,
    nombre: "Peonía Whisper",
    categoria: "Floral",
    imagen: "../img/img8.png",
    codigo: "PE11R6",
    precio: 70000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Verano",
    stock: 22,
  },
  {
    id: 51,
    nombre: "Guayaco Bark",
    categoria: "Amaderado",
    imagen: "../img/img2.png",
    codigo: "GU47Z1",
    precio: 80000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Otoño",
    stock: 40,
  },
  {
    id: 52,
    nombre: "Mirra Gold",
    categoria: "Oriental",
    imagen: "../img/img9.png",
    codigo: "MI73X7",
    precio: 60000,
    volumen: 100,
    intensidad: "Media",
    genero: "Masculino",
    temporada: "Invierno",
    stock: 15,
  },
  {
    id: 53,
    nombre: "Melocotón Bliss",
    categoria: "Frutal",
    imagen: "../img/img5.png",
    codigo: "ME99B4",
    precio: 110000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Primavera",
    stock: 54,
  },
  {
    id: 54,
    nombre: "Almendra Sensation",
    categoria: "Gourmand",
    imagen: "../img/img1.png",
    codigo: "AL25N9",
    precio: 90000,
    volumen: 50,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Primavera",
    stock: 54,
  },
  {
    id: 55,
    nombre: "Pomelo Spark",
    categoria: "Cítrico",
    imagen: "../img/img7.png",
    codigo: "PO51V2",
    precio: 80000,
    volumen: 100,
    intensidad: "Media",
    genero: "Unisex",
    temporada: "Verano",
    stock: 29,
  },
  {
    id: 56,
    nombre: "Lirio Bloom",
    categoria: "Floral",
    imagen: "../img/img3.png",
    codigo: "LI87Q8",
    precio: 60000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Otoño",
    stock: 41,
  },
  {
    id: 57,
    nombre: "Cedro Earth",
    categoria: "Amaderado",
    imagen: "../img/img10.png",
    codigo: "CE13L5",
    precio: 110000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Masculino",
    temporada: "Invierno",
    stock: 18,
  },
  {
    id: 58,
    nombre: "Cardamomo Mystic",
    categoria: "Oriental",
    imagen: "../img/img6.png",
    codigo: "CA49U1",
    precio: 90000,
    volumen: 100,
    intensidad: "Media",
    genero: "Unisex",
    temporada: "Primavera",
    stock: 52,
  },
  {
    id: 59,
    nombre: "Higo Tart",
    categoria: "Frutal",
    imagen: "../img/img4.png",
    codigo: "HI75O7",
    precio: 70000,
    volumen: 30,
    intensidad: "Fuerte",
    genero: "Femenino",
    temporada: "Verano",
    stock: 25,
  },
  {
    id: 60,
    nombre: "Vainilla Delight",
    categoria: "Gourmand",
    imagen: "../img/img8.png",
    codigo: "VA91I3",
    precio: 80000,
    volumen: 50,
    intensidad: "Suave",
    genero: "Unisex",
    temporada: "Otoño",
    stock: 36,
  },
];
